# 🔢 NumPy: From Zero to Hero
> **A hands-on learning notebook for beginners**

---

**NumPy** (Numerical Python) is the core library for scientific computing in Python.  
It provides a powerful N-dimensional array object and tools for working with these arrays.

### 📚 What you'll learn:
| Module | Topic |
|--------|-------|
| 1 | Array Creation & Basics |
| 2 | Indexing & Slicing |
| 3 | Math & Statistics Operations |
| 4 | Reshaping & Broadcasting |

### 🏷️ Cell Legend:
- 📖 **Theory** — Explanation + demo code  
- ✏️ **Practice** — You write the code  
- 🐛 **Fix the Bug** — Find and fix the error  
- 🔍 **Predict** — What will the output be?  
- ✅ **Check** — Run this to verify your answer


In [1]:
# ▶️ Run this first — imports NumPy
import numpy as np
print('NumPy version:', np.__version__)
print('✅ NumPy is ready!')

NumPy version: 2.0.2
✅ NumPy is ready!


---
## 📦 Module 1: Array Creation & Basics

### 1.1 What is a NumPy Array?

A NumPy **ndarray** is a grid of values, all of the **same type**, indexed by a tuple of non-negative integers.

| Feature | Python List | NumPy Array |
|---------|------------|-------------|
| Type | Mixed allowed | Same type (homogeneous) |
| Speed | Slower | Much faster |
| Memory | More | Less |
| Math ops | Manual loop | Built-in vectorized |

### 1.2 Key Vocabulary
- **ndim** — number of dimensions (axes)
- **shape** — size along each dimension, e.g. `(3, 4)`
- **dtype** — data type of elements, e.g. `int64`, `float32`
- **size** — total number of elements


In [2]:
# 📖 THEORY DEMO — Creating arrays and inspecting them

# 1D array
a = np.array([1, 2, 3, 4, 5])
print('1D array:', a)
print('  ndim:', a.ndim)   # 1
print('  shape:', a.shape) # (5,)
print('  dtype:', a.dtype) # int64
print()

1D array: [1 2 3 4 5]
  ndim: 1
  shape: (5,)
  dtype: int64



In [3]:
# 2D array (matrix)
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print('2D array:\n', b)
print('  ndim:', b.ndim)   # 2
print('  shape:', b.shape) # (2, 3)
print('  size:', b.size)   # 6

2D array:
 [[1 2 3]
 [4 5 6]]
  ndim: 2
  shape: (2, 3)
  size: 6


In [4]:
# 📖 THEORY DEMO — Special array creation functions

print(np.zeros((2, 3)))        # All zeros
print()
print(np.ones((3, 3)))         # All ones
print()
print(np.eye(4))               # Identity matrix

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
print(np.arange(0, 10, 2))     # Like range() → [0 2 4 6 8]
print()
print(np.linspace(0, 1, 5))    # 5 evenly spaced values from 0 to 1
print()
print(np.full((2,4), 7))       # Fill with a constant value

[0 2 4 6 8]

[0.   0.25 0.5  0.75 1.  ]

[[7 7 7 7]
 [7 7 7 7]]


### ✏️ Practice 1.1 — Create Arrays

Complete each task below using NumPy functions.

In [6]:
# ✏️ TASK 1: Create a 1D array of numbers from 1 to 10 (inclusive)
# Expected: [ 1  2  3  4  5  6  7  8  9 10]

#task1 = np.array([1,2,3,4,5,6,7,8,9,10])
task1 =
print('Task 1:', task1)

Task 1: [ 1  2  3  4  5  6  7  8  9 10]


In [7]:
# ✏️ TASK 2: Create a 3x3 matrix filled with zeros
# Expected:
# [[0. 0. 0.]
#  [0. 0. 0.]
#  [0. 0. 0.]]

task2 = np.zeros((3, 3))
print('Task 2:\n', task2)

Task 2:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# ✏️ TASK 3: Create an array of 6 evenly spaced values between 0 and 100
# Expected: [  0.  20.  40.  60.  80. 100.]

task3 = # ✍️ your code here
print('Task 3:', task3)

In [ ]:
# ✅ CHECK — Run this to verify your answers
assert list(task1) == list(range(1, 11)), '❌ Task 1 failed'
assert task2.shape == (3, 3) and task2.sum() == 0, '❌ Task 2 failed'
assert len(task3) == 6 and task3[0] == 0 and task3[-1] == 100, '❌ Task 3 failed'
print('✅ All tasks passed!')

### 🐛 Fix the Bug 1.1

The code below has **2 bugs**. Find and fix them!

In [ ]:
# 🐛 FIX THE BUG — This code should create a 4x4 identity matrix
# and print its shape and the sum of its diagonal

identity = np.eye(4, 4)          # Bug 1: eye() only needs ONE argument for square matrix — or does it?
print('Shape:', identity.shape()  # Bug 2: shape is a property, not a method
print('Diagonal sum:', np.sum(np.diag(identity)))

---
## 🔎 Module 2: Indexing & Slicing

### 2.1 Indexing Basics

NumPy uses **zero-based indexing** just like Python lists.  
For 2D arrays, indexing works as `array[row, col]`.

```
       col→   0   1   2
row ↓  0  [ 10  20  30 ]
       1  [ 40  50  60 ]
       2  [ 70  80  90 ]

array[1, 2]  → 60   (row 1, col 2)
array[-1, 0] → 70   (last row, first col)
```

### 2.2 Slicing Syntax
```python
array[start:stop:step]   # 1D
array[r_start:r_stop, c_start:c_stop]  # 2D
```
- `start` is **inclusive**, `stop` is **exclusive**
- Omitting `start` defaults to 0; omitting `stop` goes to end

### 2.3 Boolean Masking
You can filter arrays using a condition — this returns only matching elements.
```python
a[a > 5]   # elements greater than 5
```


In [ ]:
# 📖 THEORY DEMO — Indexing and slicing

m = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])

print('Full matrix:\n', m)
print()

In [ ]:
print('Element at row 0, col 2:', m[0, 2])      # 30
print('Last row:', m[-1, :])                     # [70 80 90]

In [ ]:
print('First column:', m[:, 0])                  # [10 40 70]
print('Sub-matrix (top-right 2x2):\n', m[0:2, 1:3])  # [[20 30],[50 60]]
print()
# Boolean masking
print('Elements > 45:', m[m > 45])               # [50 60 70 80 90]

### 🔍 Predict the Output 2.1

**Before running** each cell, write down what you think the output will be in the comment.  
Then run the cell to check!

In [ ]:
# 🔍 PREDICT — What is the output?
x = np.arange(10)   # [0 1 2 3 4 5 6 7 8 9]

# Write your prediction as a comment before running!
print(x[2:7])       # Prediction: ?
print(x[::3])       # Prediction: ?
print(x[::-1])      # Prediction: ?

In [ ]:
# 🔍 PREDICT — 2D slicing
grid = np.arange(1, 10).reshape(3, 3)
# grid is:
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]

print(grid[1, :])    # Prediction: ?
print(grid[:, 2])    # Prediction: ?
print(grid[::2, ::2]) # Prediction: ?

### ✏️ Practice 2.1 — Indexing & Slicing

In [ ]:
# Setup for practice tasks
data = np.array([[5, 10, 15, 20],
                 [25, 30, 35, 40],
                 [45, 50, 55, 60],
                 [65, 70, 75, 80]])
print('data matrix:\n', data)

In [ ]:
# ✏️ TASK 1: Extract the value 55 from the matrix
val = # ✍️ your code here
print('Value:', val)  # Expected: 55

In [ ]:
# ✏️ TASK 2: Extract the entire third column (index 2)
col = # ✍️ your code here
print('Column 2:', col)  # Expected: [15 35 55 75]

In [ ]:
# ✏️ TASK 3: Extract the bottom-right 2x2 sub-matrix
sub = # ✍️ your code here
print('Sub-matrix:\n', sub)
# Expected:
# [[55 60]
#  [75 80]]

In [ ]:
# ✏️ TASK 4: Use boolean masking to get all values greater than 50
filtered = # ✍️ your code here
print('Values > 50:', filtered)  # Expected: [55 60 65 70 75 80]

---
## ➕ Module 3: Math & Statistics Operations

### 3.1 Element-wise Arithmetic

NumPy operations work **element-by-element** — no loops needed!

```python
a + b   → adds each pair of elements
a * b   → multiplies each pair
a ** 2  → squares each element
```

### 3.2 Universal Functions (ufuncs)
NumPy has built-in math functions that apply to entire arrays:

| Function | Description |
|----------|-------------|
| `np.sqrt(a)` | Square root of each element |
| `np.abs(a)` | Absolute value |
| `np.exp(a)` | e^x for each element |
| `np.log(a)` | Natural log |
| `np.sin(a)`, `np.cos(a)` | Trig functions |

### 3.3 Aggregate / Statistics

| Function | Description |
|----------|-------------|
| `np.sum(a)` | Sum of all elements |
| `np.mean(a)` | Average |
| `np.median(a)` | Median |
| `np.std(a)` | Standard deviation |
| `np.min(a)` / `np.max(a)` | Min/Max |
| `np.argmin(a)` / `np.argmax(a)` | Index of min/max |

> 💡 **Tip:** Add `axis=0` to aggregate **column-wise**, `axis=1` for **row-wise**.


In [ ]:
# 📖 THEORY DEMO — Arithmetic and ufuncs

a = np.array([1, 4, 9, 16, 25])
b = np.array([2, 2, 3, 4, 5])

print('a + b =', a + b)
print('a * b =', a * b)
print('a / b =', a / b)
print('a ** 0.5 =', a ** 0.5)  # same as sqrt
print('np.sqrt(a) =', np.sqrt(a))
print('np.abs([-3,1,-5]) =', np.abs([-3, 1, -5]))

In [ ]:
# 📖 THEORY DEMO — Statistics with axis parameter

scores = np.array([[85, 90, 78],
                   [70, 65, 88],
                   [92, 95, 80]])

print('All scores mean:', np.mean(scores))          # overall average
print('Mean per column (per subject):', np.mean(scores, axis=0))  # 3 values
print('Mean per row (per student):', np.mean(scores, axis=1))     # 3 values
print('Max score:', np.max(scores))
print('Std deviation:', np.std(scores).round(2))

### ✏️ Practice 3.1 — Math Operations

In [ ]:
# Setup
temps_celsius = np.array([0, 10, 20, 30, 37, 100])
nums = np.array([-5, -2, 0, 3, 7, 10, -8, 4])

In [ ]:
# ✏️ TASK 1: Convert Celsius to Fahrenheit
# Formula: F = C * 9/5 + 32
# Expected: [32. 50. 68. 86. 98.6 212.]

temps_f = # ✍️ your code here
print('Fahrenheit:', temps_f)

In [ ]:
# ✏️ TASK 2: From 'nums', extract only the positive numbers, then find their sum
# Hint: use boolean masking first
# Expected sum: 24

positive_sum = # ✍️ your code here
print('Sum of positives:', positive_sum)

In [ ]:
# ✏️ TASK 3: Given this exam scores matrix, find the highest scorer per student (row max)
exam = np.array([[55, 72, 88],
                 [91, 64, 77],
                 [45, 89, 93]])

best_per_student = # ✍️ your code here
print('Best score per student:', best_per_student)  # Expected: [88 91 93]

### 🐛 Fix the Bug 3.1

In [ ]:
# 🐛 FIX THE BUG — This should normalize the data (subtract mean, divide by std)
# and then print the mean and std of the result (should be ~0 and ~1)

raw = np.array([10, 20, 30, 40, 50])

normalized = raw - np.mean(raw) / np.std(raw)   # Bug: operator precedence!
print('Mean (should be ~0):', np.mean(normalized).round(5))
print('Std  (should be ~1):', np.std(normalized).round(5))

---
## 🔄 Module 4: Reshaping & Broadcasting

### 4.1 Reshaping Arrays

`reshape(new_shape)` changes the shape of an array **without changing the data**.

```
[1 2 3 4 5 6]  →  [[1 2 3]      →  [[[1 2]
                    [4 5 6]]          [3 4]]
                                      [[5 6]]]
shape: (6,)       shape: (2,3)        shape: (3,2,...)
```

> 💡 Use `-1` as a wildcard dimension — NumPy infers it automatically.
> `a.reshape(2, -1)` → 2 rows, NumPy figures out columns.

### 4.2 Flatten & Ravel
- `a.flatten()` — returns a **copy** as 1D array
- `a.ravel()` — returns a **view** as 1D array (more memory efficient)

### 4.3 Broadcasting

Broadcasting lets NumPy operate on arrays of **different shapes** by automatically expanding the smaller one.

```
Shape (3, 3) + Shape (3,)  →  adds the 1D array to each row
Shape (3, 1) + Shape (1, 3) →  creates a (3, 3) result
```

**Rules:**
1. If shapes have different lengths, pad on the **left** with 1s
2. Dimensions of size 1 are stretched to match the other
3. If dimensions don't match and neither is 1 → **error**


In [ ]:
# 📖 THEORY DEMO — Reshaping

a = np.arange(1, 13)     # [1 2 3 ... 12]
print('Original:', a, '  shape:', a.shape)
print()

b = a.reshape(3, 4)      # 3 rows, 4 cols
print('Reshaped to (3,4):\n', b)
print()

c = a.reshape(2, -1)     # 2 rows, auto cols
print('Reshaped to (2,-1):\n', c, '  shape:', c.shape)
print()

print('Flattened:', b.flatten())

In [ ]:
# 📖 THEORY DEMO — Broadcasting

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_add = np.array([10, 20, 30])   # shape (3,)

print('Matrix + row_add (broadcasts across rows):')
print(matrix + row_add)
print()

col_add = np.array([[10], [20], [30]])  # shape (3,1)
print('Matrix + col_add (broadcasts across columns):')
print(matrix + col_add)

### 🔍 Predict the Output 4.1

In [ ]:
# 🔍 PREDICT — What shape will result?
x = np.ones((4, 1))
y = np.ones((1, 3))
z = x + y

# Write your prediction before running!
print('Shape of z:',  z.shape)   # Prediction: ?
print('Content:\n', z)           # Prediction: ?

### ✏️ Practice 4.1 — Reshaping & Broadcasting

In [ ]:
# ✏️ TASK 1: Reshape a 1D array of 20 elements into a 4x5 matrix
arr = np.arange(1, 21)

matrix = # ✍️ your code here
print('Reshaped matrix:\n', matrix)
print('Shape:', matrix.shape)   # Expected: (4, 5)

In [ ]:
# ✏️ TASK 2: Flatten the matrix back to 1D
flat = # ✍️ your code here
print('Flattened:', flat)  # Expected: [ 1  2  3 ... 20]

In [ ]:
# ✏️ TASK 3: Using broadcasting, subtract the row mean from each row of this matrix
# This is called 'mean-centering' — each row should then have a mean of 0

m = np.array([[1, 2, 3],
              [10, 20, 30],
              [7, 5, 3]])

# Hint: compute row means with axis=1, then reshape to (3,1) for broadcasting
row_means = # ✍️ step 1: compute row means
centered  = # ✍️ step 2: subtract row means using broadcasting

print('Centered matrix:\n', centered)
print('Row means of result (should all be 0):', np.mean(centered, axis=1))

---
## 🏆 Final Challenge — Put It All Together!

You are given a dataset of student marks. Use everything you've learned to answer the questions below.

In [ ]:
# Dataset: 5 students × 4 subjects (Math, Science, English, History)
marks = np.array([
    [78, 85, 90, 70],   # Student 0
    [55, 60, 72, 65],   # Student 1
    [91, 88, 76, 95],   # Student 2
    [40, 55, 60, 48],   # Student 3
    [82, 79, 88, 85],   # Student 4
])
subjects = ['Math', 'Science', 'English', 'History']
print('Marks matrix shape:', marks.shape)

In [ ]:
# 🏆 Q1: What is the average mark for each subject?
subject_avg = # ✍️ your code here
for s, avg in zip(subjects, subject_avg):
    print(f'  {s}: {avg:.1f}')

In [ ]:
# 🏆 Q2: Which student has the highest overall average?
student_avg = # ✍️ compute average per student
top_student  = # ✍️ find index of highest average
print(f'Top student: Student {top_student} with avg {student_avg[top_student]:.1f}')

In [ ]:
# 🏆 Q3: Which students scored below 60 in at least one subject?
# Hint: use boolean operations; np.any() with axis=1 checks if ANY column is True per row
struggling = # ✍️ your code here
print('Students with at least one score < 60:', np.where(struggling)[0])

In [ ]:
# 🏆 Q4: Normalize all marks to a 0–1 scale using min-max normalization
# Formula: (x - min) / (max - min)
normalized = # ✍️ your code here
print('Normalized marks:\n', normalized.round(3))
print('Min value (should be 0.0):', normalized.min())
print('Max value (should be 1.0):', normalized.max())

# **Loading and Storing Numpy Array**

In [ ]:
import numpy as np

# Create some example NumPy arrays
data1 = np.array([1, 2, 3, 4, 5])
data2 = np.arange(10, 20).reshape(2, 5)

print("Original data1:\n", data1)
print("Original data2:\n", data2)

Original data1:
 [1 2 3 4 5]
Original data2:
 [[10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
# --- Storing and Loading a Single NumPy Array ---

# Save a single array to a binary file in .npy format
np.save('my_array.npy', data1)
print("Saved data1 to 'my_array.npy'")

# Load the array back from the file
loaded_data1 = np.load('my_array.npy')
print("Loaded single array:\n", loaded_data1)

Saved data1 to 'my_array.npy'
Loaded single array:
 [1 2 3 4 5]


In [ ]:
# Save multiple arrays into a single .npz archive
# You can give them names (keywords) which will be used to access them later
np.savez('multiple_arrays.npz', array1=data1, array2=data2)
print("Saved data1 and data2 to 'multiple_arrays.npz'")

Saved data1 and data2 to 'multiple_arrays.npz'


In [ ]:
# Load the .npz archive
# This returns a NpzFile object, which is like a dictionary
loaded_archive = np.load('multiple_arrays.npz')

# Access the arrays by their given names
loaded_data1_from_archive = loaded_archive['array1']
loaded_data2_from_archive = loaded_archive['array2']

print("Loaded array1 from archive:\n", loaded_data1_from_archive)
print("Loaded array2 from archive:\n", loaded_data2_from_archive)

# Don't forget to close the NpzFile object if you opened it (optional, but good practice)
# loaded_archive.close() # Often not strictly necessary in simple scripts, but good for large files

# You can also list the content of the archive
print("Arrays in the archive:", loaded_archive.files)


Loaded array1 from archive:
 [1 2 3 4 5]
Loaded array2 from archive:
 [[10 11 12 13 14]
 [15 16 17 18 19]]
Arrays in the archive: ['array1', 'array2']


---
## 📋 Quick Reference Summary

| Topic | Key Functions |
|-------|---------------|
| **Create** | `np.array()`, `np.zeros()`, `np.ones()`, `np.eye()`, `np.arange()`, `np.linspace()` |
| **Inspect** | `.shape`, `.ndim`, `.dtype`, `.size` |
| **Index/Slice** | `a[i]`, `a[i,j]`, `a[start:stop:step]`, `a[a > val]` |
| **Math** | `np.sqrt()`, `np.abs()`, `np.exp()`, `np.log()` |
| **Stats** | `np.sum()`, `np.mean()`, `np.std()`, `np.min()`, `np.max()`, `np.argmax()` |
| **Reshape** | `.reshape()`, `.flatten()`, `.ravel()` |
| **Broadcasting** | Shapes must be compatible — pad left with 1s, stretch dims of size 1 |

---
*🎉 Congratulations on completing the NumPy notebook!*
